### ISSUE TITLE
Umlaute im Stundenplan

### ISSUE THREAD

**Issue by nagorczak** [avinotec/Stundenplaner.FHE_EAH#6]
Umlaute wie ä, ö, ü werden nicht mit dem richtigen Charset geparsed wodurch Namen und Übungsangaben ("Ü") falsch dargestellt werden

- [x] im Stundenplan
- [x] in Anzeige "Mein Stundenplan"
- [x] im Dialog "Add Lesson" Vorlesungstitel korrigieren
- [x] im "Add Lesson"-Menü in "Mein Stundenplan" (Raum korrigieren - Bsp. AO/UT/UTE "Hörsaal Ziegelmühlenweg")

**Comment by nagorczak** [comment]
Bisherige Überlegung: Mit Herrn Avemarg sprechen, ob wir mit Informationen aus oder Änderungen in Erfurt das Problem beheben können.

**Comment by nagorczak** [comment]
Vorrübergehende Lösung (@avinotec, funktioniert doch.):
An entsprechender Stelle (`TimeTableEvntItem.java`) werden Personen- und Vorlesungsnamen überprüft und falsche Darstellungen durch die korrekten Umlaute ersetzt.

**Comment by Avemarg** [comment]
Die fehlerhaften Umlaute finden sich bereits in den Rohdaten, welche der App-Server importiert. 

Beispiel: 

- Bachelor Biotechnologie - BT(BA)1 - Gruppe BT(BA)1.01
- URL der Kalender-/Stundenplandaten: [https://stundenplanung.eah-jena.de/ical/studentset/SPLUS4E14DD.ics](https://stundenplanung.eah-jena.de/ical/studentset/SPLUS4E14DD.ics)
- Auszug aus den Daten: `DESCRIPTION:Dozent: Hoechstetter\, MÃ¼ller\,Th.\n`

Hier sollte idealerweise das ServiceZentrum für Informatik Abhilfe schaffen.
